import React, { useRef, useState } from 'react';
import { UploadCloud, FileJson, AlertCircle } from 'lucide-react';

interface Props {
  onDataLoaded: (data: any) => void;
  onUseDemo: () => void;
}

export const UploadZone: React.FC<Props> = ({ onDataLoaded, onUseDemo }) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [error, setError] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);

  const processFile = (file: File) => {
    setError(null);
    if (file.type !== "application/json" && !file.name.endsWith('.json')) {
      setError("Please upload a valid JSON file.");
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const json = JSON.parse(e.target?.result as string);
        if (!json.top_issues || !json.run_window) {
          setError("JSON does not match the HCR Report Schema.");
          return;
        }
        onDataLoaded(json);
      } catch (err) {
        setError("Failed to parse JSON.");
      }
    };
    reader.readAsText(file);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      processFile(e.dataTransfer.files[0]);
    }
  };

  return (
    <div className="min-h-[60vh] flex flex-col items-center justify-center p-6">
      <div className="max-w-md w-full text-center space-y-8">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold text-slate-900 serif">HCR Sentiment Tracker</h1>
          <p className="text-slate-500">Visualize weekly political sentiment analysis generated by Gemini.</p>
        </div>

        <div 
          className={`
            border-2 border-dashed rounded-xl p-10 transition-colors cursor-pointer
            flex flex-col items-center justify-center gap-4
            ${isDragging ? 'border-indigo-500 bg-indigo-50' : 'border-slate-300 hover:border-indigo-400 hover:bg-slate-50'}
          `}
          onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
          onDragLeave={() => setIsDragging(false)}
          onDrop={handleDrop}
          onClick={() => fileInputRef.current?.click()}
        >
          <div className="bg-slate-100 p-4 rounded-full">
            <UploadCloud className="w-8 h-8 text-slate-500" />
          </div>
          <div>
            <p className="font-medium text-slate-900">Click to upload analysis JSON</p>
            <p className="text-sm text-slate-500">or drag and drop file here</p>
          </div>
          <input 
            type="file" 
            ref={fileInputRef} 
            className="hidden" 
            accept=".json"
            onChange={(e) => e.target.files?.[0] && processFile(e.target.files[0])}
          />
        </div>

        {error && (
          <div className="bg-rose-50 text-rose-600 p-3 rounded-lg text-sm flex items-center justify-center gap-2">
            <AlertCircle className="w-4 h-4" />
            {error}
          </div>
        )}

        <div className="relative">
          <div className="absolute inset-0 flex items-center">
            <span className="w-full border-t border-slate-200" />
          </div>
          <div className="relative flex justify-center text-xs uppercase">
            <span className="bg-[#f8fafc] px-2 text-slate-500">Or start exploring</span>
          </div>
        </div>

        <button 
          onClick={onUseDemo}
          className="w-full py-2.5 px-4 bg-white border border-slate-300 text-slate-700 font-medium rounded-lg hover:bg-slate-50 hover:text-slate-900 transition-colors flex items-center justify-center gap-2 shadow-sm"
        >
          <FileJson className="w-4 h-4" />
          Load Demo Report
        </button>
      </div>
    </div>
  );
};
